[project]
name = "isotropic"
version = "0.1.0"
description = "Analysis of isotropic errors in QC algorithms"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jax>=0.7.0",
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
    "pytest>=8.4.1",
    "scipy>=1.16.0",
]
